// <auto-generated />
using System;
using LinguaFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinguaFlow.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LinguaFlowDbContext))]
    [Migration("20260826212328_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("LinguaFlow.Core.ConversationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("LinguaFlow.Core.ConversationSession", b =>
                {
                    b.OwnsMany("LinguaFlow.Core.ConversationTurn", "Turns", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("SessionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("SessionId");

                            b1.ToTable("Turns", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SessionId");

                            b1.OwnsMany("LinguaFlow.Core.Correction", "Corrections", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Corrected")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Explanation")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Original")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("TurnId")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("TurnId");

                                    b2.ToTable("Corrections", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("TurnId");
                                });

                            b1.Navigation("Corrections");
                        });

                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
